### PR TITLE
Box arguments taking into consideration deep pointers

### PR DESCRIPTION
**Pull request by vixalien**
In GI, some values are nested in pointers, while others are not.

### Direct values (no pointers)

For example, given a function like the following:

```c
gdouble get_double() {}
```

To unbox the value above, you will just need to do `dataView.getFloat64()`.

### pointers

This is usually common in outArgs

```c
void get_double(gdouble *out) {}
```

To unbox the argument above, we need to get the value pointed to, and then finally get the value.

```js
const pointer = cast_u64_ptr(dataView.getBigUint64());
const pointed_to = deref_buf(pointer, 8);
pointed_to.getFloat64();
```

### Doubly pointed to values

```c
void get_double(gdouble **out) {}
```

While extremely rare, it is possible that values are contained in a pointer to a pointer. To check for these values, we use [`GITypeInfo.is_pointer`](https://gnome.pages.gitlab.gnome.org/gobject-introspection/girepository/gi-GITypeInfo.html#g-type-info-is-pointer). Here is an example of this usage: https://gitlab.gnome.org/GNOME/gobject-introspection/-/blob/main/tests/scanner/regress.c?ref_type=heads#L647

Because `out` (and `inout`) arguments are already pointers, if such an argument has `is_pointer()` set to true, it effectively means it's a pointer to a pointer.

> Note that the types of [GI_DIRECTION_OUT](https://gnome.pages.gitlab.gnome.org/gobject-introspection/girepository/gi-GIArgInfo.html#GI-DIRECTION-OUT:CAPS) and [GI_DIRECTION_INOUT](https://gnome.pages.gitlab.gnome.org/gobject-introspection/girepository/gi-GIArgInfo.html#GI-DIRECTION-INOUT:CAPS) parameters will only be pointers if the underlying type being transferred is a pointer (i.e. only if the type of the C function’s formal parameter is a pointer to a pointer).

To unbox these values, we need to double get the value, as implemented in this PR with a new value called `nPointers`.

```js
const pointer = cast_u64_ptr(dataView.getBigUint64());
const pointed_to = deref_buf(pointer_view, 8);

const pointer2 = cast_u64_buf(new ExtendedDataView(pointed_to).getBigUint64());
const pointed_to2 = deref_buf(pointer2, 8);

pointed_to2.getFloat64();
```

I've also added a GStreamer example, as that should be interesting...

### CODE REVIEW

**Comment by vixalien** [comment]
I've also added various array tests for strings like strings, GTypes, etc...

I think this should be reviewed so that I can start working on the next batch of tests

**Comment by ahgilak** [comment]
running gstreamer example results in segmentation fault

**Comment by vixalien** [comment]
you're right. this is due to GStreamer's insistence on passing everything as pointers. working on it

**Comment by vixalien** [comment]
Hello. I haven't been able to diagnose what's wrong with GStreamer and I would suggest we merge this as-is (probably removing the gstreamer code) as other parts work.

This would allow us to iterate on other parts faster.

**Comment by vixalien** [comment]
ping

**Comment by ahgilak** [comment]
so is this ready to merge now?

**Comment by vixalien** [comment]
Yes, I guess. The GStreamer demo will still be (intentionally) broken though.

**Comment by ahgilak** [comment]
running gstreamer example outside this PR on the main branch returns the following error
`error: Uncaught (in promise) GLib.Error [Too few "out" arguments (handling inout)] {}`
so we are handling inout arguments wrong
but I don't know why running on this PR returns segfault instead of showing this error

**Comment by ahgilak** [comment]
hello @vixalien 

since I don't have enough time to maintain this project alone, and you did a great job with your contributions, I wanted to add you as a collaborator so you could merge and maintain codes. are you okay with that?

**Comment by vixalien** [comment]
Hello. no worries. Do you have a matrix account or other chat so that we can communicate more easily?

**Comment by ahgilak** [comment]
I'm not active on matrix. you can reach me via email ah.gilak@outlook.com or telegram [ahgilak](https://t.me/ahgilak)

**Pull request merged**
