### PR TITLE
Use underscore_case instead of camelCase

### LINKED ISSUE #4: Use `connect` instead of `on`
Hello. Very lovely project!

I think it would be better if the project recommended the use of `connect` and `disconnect` instead of the archaic node-style `on` and `off`. This would make it more consistent with GObject signals and how they are handled in GJS.

### PR DESCRIPTION
**Pull request by vixalien**
Instead of `GObject.doSomething()`, it's `GObject.do_something()` which is similar to GJS.

fix #4 

should I also use `connect` and `disconnect` instead of `on` and `off` respectively?

### CODE REVIEW

**Comment by ahgilak** [comment]
> should I also use `connect` and `disconnect` instead of `on` and `off` respectively?

do you mean in the examples? yeah it's okay.
but keep the on and off methods available in source code for optional use

**Comment by vixalien** [comment]
ptal!

**Comment by vixalien** [comment]
After this is merged, you will need to update https://gir.deno.dev to return the `X-TypeScript-Types` header in the format `@girs/gtk-4.0` instead of the current `@girs/node-gtk-4.0`

**Comment by ahgilak** [comment]
gjs supports camel case, underscore and also hyphens (when using strings) for properties.
can the same behavior be implemented?

https://gjs.guide/guides/gjs/style-guide.html#gobject
```js
label.useMarkup = true;

label.bind_property('use-markup', label, 'use-underline',
    GObject.BindFlags.SYNC_CREATE | GObject.BindFlags.INVERT_BOOLEAN);
```

**Comment by vixalien** [comment]
imo that behaviour is inconsistent in my experience and i think some
projects (like gi-ts) don’t prefer that as it leads to bizarre cases where
inconsistent parameters are used. I’m in favour of using just one property,
as this feature doesn’t bring any good benefits except confusion.

I’m happy to close this PR if you feel this is not the direction you want
to go with.

**Comment by ahgilak** [comment]
> I’m happy to close this PR if you feel this is not the direction you want
to go with.

No you made a fair point.

**Comment by ahgilak** [comment]
so is this ready to merge now?

**Comment by vixalien** [comment]
yes it's ready to merge :)

**Pull request merged**
